name: "Development flow for testing and merging"

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  security:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build .Net
        uses: actions/setup-dotnet@v1
      - name: build the project
        run: |
          dotnet build
          dotnet --version
      - uses: snyk/actions/setup@master
      - name: Test dependencies with Snyk
        run: snyk test --all-projects --detection-level=2
        env:
          SNYK_TOKEN: 5023c08e-f940-4f39-bb1c-3df81e278e67
      - name: Monitor dependencies for security issues with Snyk
        run: snyk monitor
        env:
          SNYK_TOKEN: 5023c08e-f940-4f39-bb1c-3df81e278e67
